/**
 * HOME
 */
export const FETCH_HOME_DATA = "FETCHING_HOME_DATA"
export const HOME_LOADER = "HOME_LOADER"
export const MENU_SELECTED = "MENU_SELECTED"
// export const FETCHING_HOME_DATA = "FETCHING_HOME_DATA"



export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_ERROR = "FETCHING_DATA_ERROR";